import type { FastifyInstance } from 'fastify';

export async function modelsRoute(app: FastifyInstance): Promise<void> {
  app.get('/v1/models', async () => ({
    object: 'list',
    data: [
      { id: 'auto', object: 'model', owned_by: 'proxy', description: 'Balanced default: Claude Sonnet 5.5 with Claude→Codex fallback' },
      { id: 'claude-fable-5', object: 'model', owned_by: 'anthropic', description: 'Highest-capability Claude for long-running agents' },
      { id: 'claude-opus-5-5', object: 'model', owned_by: 'anthropic', description: 'Opus 5.5 (latest) for complex reasoning and agentic coding' },
      { id: 'claude-opus-5', object: 'model', owned_by: 'anthropic', description: 'Opus 5, pinned' },
      { id: 'claude-opus-4-8', object: 'model', owned_by: 'anthropic', description: 'Previous Opus generation, pinned compatibility model' },
      { id: 'claude-opus-4-7', object: 'model', owned_by: 'anthropic', description: 'Opus 4.7 (Feb 2026), higher cost' },
      { id: 'claude-opus-4-6', object: 'model', owned_by: 'anthropic', description: 'Opus 4.6 stable (Nov 2025), ~40% cheaper than 4.7, premium quality' },
      { id: 'claude-sonnet-5-5', object: 'model', owned_by: 'anthropic', description: 'Sonnet 5.5 (latest), balanced quality/cost' },
      { id: 'claude-sonnet-5', object: 'model', owned_by: 'anthropic', description: 'Sonnet 5, pinned' },
      { id: 'claude-sonnet-4-6', object: 'model', owned_by: 'anthropic', description: 'Sonnet 4.6 stable, lower cost' },
      { id: 'claude-haiku-4-5-20251001', object: 'model', owned_by: 'anthropic', description: 'Fastest Claude, lowest cost' },
      { id: 'gpt-6.1-sol', object: 'model', owned_by: 'openai', description: 'GPT-6.1 Sol (latest flagship) via Codex OAuth' },
      { id: 'gpt-6-astra', object: 'model', owned_by: 'openai', description: 'GPT-6 Astra via Codex OAuth' },
      { id: 'gpt-6-sol', object: 'model', owned_by: 'openai', description: 'GPT-6 Sol via Codex OAuth' },
      { id: 'gpt-6-luna', object: 'model', owned_by: 'openai', description: 'GPT-6 Luna, fastest GPT via Codex OAuth' },
      { id: 'gpt-5.6-sol', object: 'model', owned_by: 'openai', description: 'GPT-5.6 flagship capability via Codex OAuth' },
      { id: 'gpt-5.6-terra', object: 'model', owned_by: 'openai', description: 'GPT-5.6 balanced quality/cost via Codex OAuth' },
      { id: 'gpt-5.6-luna', object: 'model', owned_by: 'openai', description: 'GPT-5.6 fast, high-volume tier via Codex OAuth' },
      { id: 'gpt-5.5', object: 'model', owned_by: 'openai', description: 'Previous GPT generation via Codex OAuth' },
      { id: 'gpt-5', object: 'model', owned_by: 'openai', description: 'GPT-5 stable' },
      { id: 'o3', object: 'model', owned_by: 'openai', description: 'OpenAI o3 reasoning' },
      { id: 'o4-mini', object: 'model', owned_by: 'openai', description: 'OpenAI o4-mini reasoning' },
      { id: 'gpt-4o', object: 'model', owned_by: 'openai', description: 'GPT-4o multimodal' },
    ],
    aliases: {
      'auto/smart': 'claude-sonnet-5-5 with Claude→Codex fallback',
      'opus/opus-5-5/best': 'claude-opus-5-5',
      'opus-5': 'claude-opus-5',
      'opus-4-8': 'claude-opus-4-8',
      'opus-4-7': 'claude-opus-4-7 (Feb 2026)',
      'opus-4-6': 'claude-opus-4-6 (Nov 2025 stable, ~40% cheaper than 4.7)',
      'sonnet/sonnet-5-5': 'claude-sonnet-5-5 (latest)',
      'sonnet-5': 'claude-sonnet-5',
      'fast/cheap/sonnet-4-6': 'claude-sonnet-4-6',
      'fable/fable-5': 'claude-fable-5',
      haiku: 'claude-haiku-4-5-20251001',
      'gpt-6/gpt-6.1/chatgpt': 'gpt-6.1-sol',
      'gpt-5.6': 'gpt-5.6-sol',
      'gpt-5.6-sol/terra/luna': 'OpenAI via Codex CLI with explicit model selection',
      'o3/o4-mini/gpt-4o/codex': 'Legacy OpenAI compatibility via Codex CLI',
      thinking: 'Append -thinking to any Claude model, or pass body.thinking=true',
    },
  }));
}
